### ISSUE TITLE
Solution 2 of [flatten_array] has some problem

### ISSUE THREAD

**Issue by gbhasha** [gokulkrishh/problems#1]
some (maybe, typo) issue in solution 2 of [flatten_array](https://github.com/gokulkrishh/problems/blob/master/Array/3.flatten_array.js)

The recursive call was made using 'flattenArray' but the method name is 'flatten'.
I guess the correction should be made at either the function name or the recursive call name.

```js
function flattenArray(val) {
  return val.reduce((acc, val) => {
    return acc.concat(Array.isArray(val) ? flattenArray(val) : val);
  }, []);
}
```

or 

```js
Array.prototype.flatten = function () {
  return this.reduce((acc, val) => {
    return acc.concat(Array.isArray(val) ? val.flatten() : val);
  }, []);
}
```

**Comment by gokulkrishh** [comment]
@gbhasha Yep. That's a typo 👍. Thanks for pointing it out.

**Comment by gokulkrishh** [comment]
Fixed it.
